### PR TITLE
Readme updated

### PR DESCRIPTION
**Pull request by CodeCombiner**

### CODE REVIEW

**Comment by rampr** [comment]
Alex, again all of these changes were already done in #5

**Comment by CodeCombiner** [comment]
I supposed the pull requests were merged and closed so created new one. Please close it if it is redundant.

**Comment by rampr** [comment]
The readme change in here makes sense. But I can't understand why all changes are there. But still it is showing the diff.
I can understand why commits are shown, because I did a squash and merge. But I don't understand why the diff is same as the old one.

The base repository is proper. I am trying to figure out

**Comment by rampr** [comment]
The Readme is in native-android. Closing it here.

**Pull request closed without merging**
